created: 2026-07-17 23:08:25 CEST
version: 1.3 8v
engine: FIAT/_X6H_
power_kw: 79.0
ecu: MARELLI/10GF
evidence:
- https://dev-srv.tlkeys.com/storage/files/pcmtuner/pcmtuner-detail-car-ecu-list.pdf
updated: 2026-07-17 23:08:25 CEST
