
from enum import Enum
ISO3780_WMI_COUNTRIES = {
    ("AA", "AH"): "south_africa",
    ("AJ", "AN"): "ivory_coast",
    ("BA", "BE"): "angola",
    ("BF", "BK"): "kenya",
    ("BL", "BR"): "tanzania",
    ("CA", "CE"): "benin",
    ("CF", "CK"): "madagascar",
    ("CL", "CR"): "tunisia",
    ("DA", "DE"): "egypt",
    ("DF", "DK"): "morocco",
    ("DL", "DR"): "zambia",
    ("EA", "EE"): "ethiopia",
    ("EF", "EK"): "mozambique",
    ("FA", "FE"): "ghana",
    ("FF", "FK"): "nigeria",
    ("JA", "J0"): "japan",
    ("KA", "KE"): "sri_lanka",
    ("KF", "KK"): "israel",
    ("KL", "KR"): "south_korea",
    ("LA", "L0"): "china",
    ("MA", "ME"): "india",
    ("MF", "MK"): "indonesia",
    ("ML", "MR"): "thailand",
    ("NF", "NK"): "pakistan",
    ("NL", "NR"): "turkey",
    ("PA", "PE"): "philippines",
    ("PF", "PK"): "singapore",
    ("PL", "PR"): "malaysia",
    ("RA", "RE"): "united_arab_emirates",
    ("RF", "RK"): "taiwan",
    ("RL", "RR"): "vietnam",
    ("SA", "SM"): "great_britain",
    ("SN", "ST"): "germany",
    ("SU", "SZ"): "poland",
    ("TA", "TH"): "switzerland",
    ("TJ", "TP"): "czech_republic",
    ("TR", "TV"): "hungary",
    ("TW", "T1"): "portugal",
    ("UH", "UM"): "denmark",
    ("UN", "UT"): "ireland",
    ("UU", "UZ"): "romania",
    ("U5", "U7"): "slovakia",
    ("VA", "VE"): "austria",
    ("VF", "VR"): "france",
    ("VS", "VW"): "spain",
    ("VX", "V2"): "yugoslavia",
    ("V3", "V5"): "croatia",
    ("V6", "V0"): "estonia",
    ("WA", "W0"): "germany",
    ("XA", "XE"): "bulgaria",
    ("XF", "XK"): "greece",
    ("XL", "XR"): "netherlands",
    ("XS", "XW"): "russia",
    ("XX", "X2"): "luxembourg",
    ("YA", "YE"): "belgium",
    ("YF", "YK"): "finland",
    ("YL", "YR"): "malta",
    ("YS", "YW"): "sweden",
    ("YX", "Y2"): "norway",
    ("Y3", "Y5"): "belarus",
    ("Y6", "Y0"): "ukraine",
    ("ZA", "ZR"): "italy",
    ("ZX", "Z2"): "slovenia",
    ("Z3", "Z5"): "lithuania",
    ("1A", "10"): "united_states",
    ("2A", "20"): "canada",
    ("3A", "3W"): "mexico",
    ("3X", "37"): "costa_rica",
    ("4A", "40"): "united_states",
    ("5A", "50"): "united_states",
    ("6A", "6W"): "australia",
    ("7A", "7E"): "new_zealand",
    ("8A", "8E"): "argentina",
    ("8F", "8K"): "chile",
    ("8L", "8R"): "ecuador",
    ("8S", "8W"): "peru",
    ("8X", "82"): "venezuela",
    ("9A", "9E"): "brazil",
    ("9F", "9K"): "colombia",
    ("9L", "9R"): "paraguay",
    ("9S", "9W"): "uruguay",
    ("9X", "92"): "trinidad_&_tobago",
    ("93", "99"): "brazil",
}

class ISO3780_WMI_REGION(Enum):
    africa = 1
    asia = 2
    europe = 3
    north_america = 4
    oceania = 5
    south_america = 6
    unknown = 7

ISO3780_WMI_REGIONS = {
    ("A","H"): ISO3780_WMI_REGION.africa,
    ("J","R"): ISO3780_WMI_REGION.asia,
    ("S","Z"): ISO3780_WMI_REGION.europe,
    ("1","5"): ISO3780_WMI_REGION.north_america,
    ("6","7"): ISO3780_WMI_REGION.oceania,
    ("8","9"): ISO3780_WMI_REGION.south_america
}