
from enum import Enum
ISO3780_WMI_COUNTRIES = {
    ("AA", "AH"): ("south_africa", "ZAF"),
    ("AJ", "AN"): ("ivory_coast", "CIV"),
    ("BA", "BE"): ("angola", "AGO"),
    ("BF", "BK"): ("kenya", "KEN"),
    ("BL", "BR"): ("tanzania", "TZA"),
    ("CA", "CE"): ("benin", "BEN"),
    ("CF", "CK"): ("madagascar", "MDG"),
    ("CL", "CR"): ("tunisia", "TUN"),
    ("DA", "DE"): ("egypt", "EGY"),
    ("DF", "DK"): ("morocco", "MAR"),
    ("DL", "DR"): ("zambia", "ZMB"),
    ("EA", "EE"): ("ethiopia", "ETH"),
    ("EF", "EK"): ("mozambique", "MOZ"),
    ("FA", "FE"): ("ghana", "GHA"),
    ("FF", "FK"): ("nigeria", "NGA"),
    ("JA", "J0"): ("japan", "JPN"),
    ("KA", "KE"): ("sri_lanka", "LKA"),
    ("KF", "KK"): ("israel", "ISR"),
    ("KL", "KR"): ("south_korea", "KOR"),
    ("LA", "L0"): ("china", "CHN"),
    ("MA", "ME"): ("india", "IND"),
    ("MF", "MK"): ("indonesia", "IDN"),
    ("ML", "MR"): ("thailand", "THA"),
    ("NF", "NK"): ("pakistan", "PAK"),
    ("NL", "NR"): ("turkey", "TUR"),
    ("PA", "PE"): ("philippines", "PHL"),
    ("PF", "PK"): ("singapore", "SGP"),
    ("PL", "PR"): ("malaysia", "MYS"),
    ("RA", "RE"): ("united_arab_emirates", "ARE"),
    ("RF", "RK"): ("taiwan", "TWN"),
    ("RL", "RR"): ("vietnam", "VNM"),
    ("SA", "SM"): ("great_britain", "GBR"),
    ("SN", "ST"): ("germany", "DEU"),
    ("SU", "SZ"): ("poland", "POL"),
    ("TA", "TH"): ("switzerland", "CHE"),
    ("TJ", "TP"): ("czech_republic", "CZE"),
    ("TR", "TV"): ("hungary", "HUN"),
    ("TW", "T1"): ("portugal", "PRT"),
    ("UH", "UM"): ("denmark", "DNK"),
    ("UN", "UT"): ("ireland", "IRL"),
    ("UU", "UZ"): ("romania", "ROU"),
    ("U5", "U7"): ("slovakia", "SVK"),
    ("VA", "VE"): ("austria", "AUT"),
    ("VF", "VR"): ("france", "FRA"),
    ("VS", "VW"): ("spain", "ESP"),
    ("VX", "V2"): ("yugoslavia", "YUG"),
    ("V3", "V5"): ("croatia", "HRV"),
    ("V6", "V0"): ("estonia", "EST"),
    ("WA", "W0"): ("germany", "DEU"),
    ("XA", "XE"): ("bulgaria", "BGR"),
    ("XF", "XK"): ("greece", "GRC"),
    ("XL", "XR"): ("netherlands", "NLD"),
    ("XS", "XW"): ("russia", "RUS"),
    ("XX", "X2"): ("luxembourg", "LUX"),
    ("YA", "YE"): ("belgium", "BEL"),
    ("YF", "YK"): ("finland", "FIN"),
    ("YL", "YR"): ("malta", "MLT"),
    ("YS", "YW"): ("sweden", "SWE"),
    ("YX", "Y2"): ("norway", "NOR"),
    ("Y3", "Y5"): ("belarus", "BLR"),
    ("Y6", "Y0"): ("ukraine", "UKR"),
    ("ZA", "ZR"): ("italy", "ITA"),
    ("ZX", "Z2"): ("slovenia", "SVN"),
    ("Z3", "Z5"): ("lithuania", "LTU"),
    ("1A", "10"): ("united_states", "USA"),
    ("2A", "20"): ("canada", "CAN"),
    ("3A", "3W"): ("mexico", "MEX"),
    ("3X", "37"): ("costa_rica", "CRI"),
    ("4A", "40"): ("united_states", "USA"),
    ("5A", "50"): ("united_states", "USA"),
    ("6A", "6W"): ("australia", "AUS"),
    ("7A", "7E"): ("new_zealand", "NZL"),
    ("8A", "8E"): ("argentina", "ARG"),
    ("8F", "8K"): ("chile", "CHL"),
    ("8L", "8R"): ("ecuador", "ECU"),
    ("8S", "8W"): ("peru", "PER"),
    ("8X", "82"): ("venezuela", "VEN"),
    ("9A", "9E"): ("brazil", "BRA"),
    ("9F", "9K"): ("colombia", "COL"),
    ("9L", "9R"): ("paraguay", "PRY"),
    ("9S", "9W"): ("uruguay", "URY"),
    ("9X", "92"): ("trinidad_&_tobago", "TTO"),
    ("93", "99"): ("brazil", "BRA"),
}

class ISO3780_WMI_REGION(Enum):
    africa = 1
    asia = 2
    europe = 3
    north_america = 4
    oceania = 5
    south_america = 6
    unknown = 7

ISO3780_WMI_REGIONS = {
    ("A","H"): ISO3780_WMI_REGION.africa,
    ("J","R"): ISO3780_WMI_REGION.asia,
    ("S","Z"): ISO3780_WMI_REGION.europe,
    ("1","5"): ISO3780_WMI_REGION.north_america,
    ("6","7"): ISO3780_WMI_REGION.oceania,
    ("8","9"): ISO3780_WMI_REGION.south_america
}